version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - TRAEFIK_ENABLE=true
      - TRAEFIK_PORT=80
      - TRAEFIK_HOST=chweb.musubi.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`chweb.musubi.dev`)"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: --log.level=DEBUG